#!/bin/bash
# Forzar reconstrucción del servicio sin caché

echo "=========================================="
echo "🔧 Forzando reconstrucción sin caché"
echo "=========================================="
echo ""

echo "1️⃣ El problema es que dashboard.html es viejo (2026-01-08)"
echo "   pero server.js está actualizado."
echo ""
echo "   Esto significa que el build no está actualizando dashboard.html."
echo ""

echo "2️⃣ Verificando fecha de dashboard.html en GitHub..."
LATEST_COMMIT=$(git ls-remote https://github.com/GermanPerez-ai/checkin24hs.git HEAD | cut -f1)
echo "Último commit en GitHub: $LATEST_COMMIT"

echo ""
echo "3️⃣ Solución: Forzar reconstrucción desde EasyPanel"
echo ""
echo "   Pasos en EasyPanel:"
echo "   1. Ve a EasyPanel → Servicio dashboard"
echo "   2. Ve a la pestaña 'Fuente' o 'Source'"
echo "   3. Verifica que:"
echo "      - Repositorio: GermanPerez-ai/checkin24hs"
echo "      - Rama: main"
echo "      - Ruta de compilación: / (raíz)"
echo "      - Tipo: Dockerfile"
echo "   4. Cambia temporalmente la rama a otra (ej: working-version)"
echo "   5. Guarda"
echo "   6. Cambia de vuelta a 'main'"
echo "   7. Guarda"
echo "   8. Haz clic en 'Deploy' o 'Redeploy'"
echo "   9. Si hay opción 'Forzar reconstrucción' o 'Force rebuild', actívala"
echo "   10. Espera 2-5 minutos"
echo ""

echo "4️⃣ Alternativa: Eliminar y recrear el servicio"
echo "   (Solo si lo anterior no funciona)"
echo ""

echo "5️⃣ Verificando si podemos forzar desde el servidor..."
echo "   (EasyPanel gestiona el servicio, así que es mejor hacerlo desde ahí)"
echo ""

echo "=========================================="
echo "📋 Resumen"
echo "=========================================="
echo ""
echo "El problema es que dashboard.html no se está actualizando en el build."
echo ""
echo "Causas posibles:"
echo "  1. EasyPanel está usando una imagen cacheada"
echo "  2. El build no está descargando el archivo actualizado de GitHub"
echo "  3. Hay un problema con el orden de las operaciones en el Dockerfile"
echo ""
echo "Solución recomendada:"
echo "  - Forzar reconstrucción desde EasyPanel (pasos arriba)"
echo "  - O eliminar y recrear el servicio si es necesario"
echo ""
