#!/bin/bash
# ⚠️ RECORDATORIO: Cómo reconfigurar IMAP de Roundcube/Webmail
# Ejecuta este script para ver los comandos clave y revisarlos antes de usarlos.

clear
echo "=============================================="
echo "⚠️  RECORDATORIO: CONFIGURAR IMAP WEBMAIL"
echo "=============================================="
echo ""
echo "📋 OBJETIVO:"
echo "Dejar Roundcube apuntando al servidor IMAP correcto"
echo "con SSL en el puerto 993, sin timeouts ni 502/504."
echo ""
echo "1️⃣  Verificar contenedor webmail actual"
echo "----------------------------------------------"
echo "En el servidor (root):"
echo ""
echo "  WEBMAIL_CONTAINER=\$(docker ps --filter \"name=webmail\" --format \"{{.ID}}\" | head -1)"
echo "  docker ps | grep -i webmail"
echo ""
echo "Debe estar en estado: replicated 1/1."
echo ""
echo "2️⃣  Variables importantes del servicio webmail (Swarm)"
echo "----------------------------------------------"
echo "Servicio: checkin24hs_webmail"
echo ""
echo "Comando recomendado:"
echo ""
echo "  docker service update \\"
echo "    --env-add ROUNDCUBEMAIL_DEFAULT_HOST=srv1152402.hstgr.cloud \\"
echo "    --env-add ROUNDCUBEMAIL_DEFAULT_PORT=993 \\"
echo "    --env-add ROUNDCUBEMAIL_DEFAULT_HOST_SSL=ssl \\"
echo "    --env-add ROUNDCUBEMAIL_SMTP_SERVER=localhost \\"
echo "    --env-add ROUNDCUBEMAIL_SMTP_PORT=587 \\"
echo "    checkin24hs_webmail"
echo ""
echo "Después de esto, verificar:"
echo ""
echo "  docker service inspect checkin24hs_webmail --pretty"
echo ""
echo "3️⃣  Limpiar labels de Traefik que fijen IPs"
echo "----------------------------------------------"
echo "Si vuelve a aparecer una IP fija tipo 10.0.1.x en Traefik:"
echo ""
echo "  docker service update \\"
echo "    --label-rm traefik.http.services.webmail.loadbalancer.server \\"
echo "    checkin24hs_webmail"
echo ""
echo "Traefik debe usar solo:"
echo "  traefik.http.services.webmail.loadbalancer.server.port=80"
echo ""
echo "4️⃣  Configuración final esperada en Roundcube"
echo "----------------------------------------------"
echo "Dentro del contenedor webmail:"
echo ""
echo "  docker exec \"\$WEBMAIL_CONTAINER\" sed -n '1,60p' /var/www/html/config/config.docker.inc.php"
echo ""
echo "Líneas importantes que DEBEN existir y estar bien escritas:"
echo ""
echo "  \$config['imap_host'] = 'ssl://srv1152402.hstgr.cloud:993';"
echo "  \$config[\"default_host\"] = \"ssl://srv1152402.hstgr.cloud\";"
echo "  \$config[\"default_port\"] = 993;"
echo ""
echo "Opcional (para certificados self-signed):"
echo ""
echo "  \$config[\"imap_conn_options\"] = ["
echo "    \"ssl\" => ["
echo "      \"verify_peer\"       => false,"
echo "      \"verify_peer_name\"  => false,"
echo "      \"allow_self_signed\" => true,"
echo "    ],"
echo "  ];"
echo ""
echo "5️⃣  Prueba rápida de IMAP (desde el contenedor webmail)"
echo "----------------------------------------------"
echo "  docker exec -it \"\$WEBMAIL_CONTAINER\" bash"
echo "  openssl s_client -connect srv1152402.hstgr.cloud:993 -crlf -quiet"
echo "  a1 LOGIN reservas@checkin24hs.com Reservas2026!@#"
echo ""
echo "Debe responder algo que termine en: \"a1 OK ... Logged in\"."
echo ""
echo "6️⃣  Verificar acceso desde el navegador"
echo "----------------------------------------------"
echo "Abrir en el navegador:"
echo "  https://webmail.checkin24hs.com/?_task=login"
echo ""
echo "Usuario:    reservas@checkin24hs.com"
echo "Contraseña: Reservas2026!@#"
echo ""
echo "Si aparece nuevamente \"error de conexión con el servidor IMAP\":"
echo "  - Verificar que el config.docker.inc.php no tenga líneas sin comillas"
echo "  - Verificar que la IP/host de IMAP siga siendo srv1152402.hstgr.cloud:993"
echo ""
echo "=============================================="
echo "Este script solo muestra recordatorios. No ejecuta cambios."
echo "Revísalos y ejecútalos manualmente cuando sea necesario."
echo "=============================================="
echo ""
